### ISSUE TITLE
'AttributeError: Namespace object has no attribute func' occurs when run some sub commands of openbmctool.py.

### ISSUE THREAD

**Issue by ping678** [openbmc/openbmc-tools#21]
Failed sub commands are fru, sensors, sel, dump, firmware.

**Comment by amboar** [comment]
@thalerj I need to get you added to the organisation so i can assign this to you

**Comment by thalerj** [comment]
@amboar Can we move this to verify? The latest pull request should have this fixed.

**Comment by amboar** [comment]
@ping678 I've merged #23 , please check that this resolves your issue as suggested by @thalerj above.

**Comment by ping678** [comment]
@thalerj The version 1.04 still fails. 
For example:
# ./openbmctool.py -H 10.100.6.110 -U root -P admin fru list
(it's OK to print fru list)

# ./openbmctool.py -H 10.100.6.110 -U root -P admin fru
 ( It throws out errors as below)

Attempting login...
Traceback (most recent call last):
  File "./openbmctool.py", line 2132, in <module>
    main()
  File "./openbmctool.py", line 2106, in main
    output = args.func(args.host, args, mysess)
AttributeError: 'Namespace' object has no attribute 'func'

Maybe the default function should be set in def createCommandParser(), like: parser_inv.set_defaults(func=fru)

**Comment by amboar** [comment]
@thalerj is this fixed?

**Comment by thalerj** [comment]
yes please close.
